name: CI

on: [workflow_dispatch]

env:
  USER_NAME: "ThisIsAUserName"

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Find and Replace - Using Secrets
      run: find dry.text -type f -exec sed -i ''s/#{CString}#/${{ env.USER_NAME }}/g'' {} \;
    - name: Bash - Show XML Contents
      run: cat dry.text
    - name: Find and Replace User Name - Using Build Variable
      run: find dry.text -type f -exec sed -i ''s/#{UName}#/${{ secrets.USER_NAME }}/g'' {} \;
    - name: Bash - Show JSON Contents
      run: cat dry.text
